---
name: Build and Publish PDF

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    environment: main
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv-gboeing.tex

      - name: Publish PDF
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: cv-gboeing.pdf
          target: ~/public_html/share
          use_insecure_cipher: true
